{
  "packages": [
    "./apps/**",
    "./packages/**",
    "./tooling/**"
  ],
  "catalog": {
    "eslint": "^10.2.0",
    "prettier": "^3.8.2",
    "zod": "^4.3.6",
    "dotenv-cli": "^11.0.0",
    "starknet": "^9.4.2",
    "viem": "^2.47.15",
    "drizzle-kit": "^0.31.10",
    "drizzle-orm": "^0.45.2",
    "typescript": "^6.0.2"
  }
}