{
  "packages": [
    "./apps/**",
    "./packages/**",
    "./tooling/**"
  ],
  "catalog": {
    "eslint": "^10.3.0",
    "prettier": "^3.8.3",
    "zod": "^3.25.76",
    "dotenv-cli": "^11.0.0",
    "starknet": "^10.0.2",
    "viem": "^2.48.8",
    "drizzle-kit": "^0.31.10",
    "drizzle-orm": "^0.45.2",
    "typescript": "^6.0.3"
  }
}