{
  "packages": [
    "./apps/**",
    "./packages/**",
    "./tooling/**"
  ],
  "catalog": {
    "eslint": "^10.0.3",
    "prettier": "^3.8.1",
    "zod": "^4.3.6",
    "dotenv-cli": "^11.0.0",
    "starknet": "^9.4.2",
    "viem": "^2.47.4",
    "drizzle-kit": "^0.31.9",
    "drizzle-orm": "^0.45.1",
    "typescript": "^5.9.3"
  }
}